apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
      type: fornt-ent
  template:
    metadata:
      labels:
        app: nginx-app
        type: fornt-ent
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
          - containerPort: 81