apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxfronend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      name: myapp-pod
    spec:
      containers:
        - image: nginx
          name: nginx-contioner