apiVersion: v1
kind: Pod
metadata:
  name: red-pod
spec:
  containers:
  - name: redis-container
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  initContainers:
  - name: busybox-container
    image: busybox
    command: ["sleep","20"]
