apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
      - name: log-volume
        mountPath: /var/log/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: claim-log-1

