apiVersion:  apps/v1
kind: Deployment
metadata:
  name: beta-pod
  namespace: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beta
  template:
    metadata:
      labels:
        app: beta
    spec:
        containers:
          - name: redis
            image: redis
            resources:
              requests:
                cpu: "0.5"
                memory: "1G"
              limits:
                cpu: "1"
                memory: "2G"
            ports:
            - containerPort: 6379