apiVersion: v1
kind: Service
metadata:
  name: creative-web
  namespace: creative
spec:
  selector:
    app: creative-web
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
